name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Scony/godot-gdscript-toolkit@4.2.2
    - run: gdlint game
    - run: gdlint menu
    - run: gdlint platform

  format:
    name: 'Format'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Scony/godot-gdscript-toolkit@4.2.2
    - run: gdformat --check game
    - run: gdformat --check menu
    - run: gdformat --check platform
